### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by flavioope** [DecentSoftware-eu/DecentHolograms3#1]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

No problems!

### Feature

I could add an option for the SOUND for example
SOUND:LEVEL_UP;2;1

It would be nice

**Comment by d0by1** [comment]
Hello, you put this in the wrong repo. Anyhow, this is already a feature, you can use the following syntax to set volme and pitch to a sound: `SOUND:<sound>:<volume>:<pitch>`

**Comment by d0by1** [comment]
Seems like there is nothing more to discuss here. I will close this issue now.
